name: Test

on: 
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Update $PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
